clients = {
    'KENNETH_DEV' : 'YEET_DEV',
    'YEET_DEV' : 'YEET2',
    'BROADCAP' : 'YEET',
    'KENNETH' : 'KFR',
    'OPAL' : 'YEET',
    'NM_SWEEP' : 'YEET',
    'GoldmanSachs-567' : 'YEET',
    'MorganStanley-890' : 'YEET',
    'BlackRock-452' : 'YEET',
    'Bridgewater-237' : 'YEET',
    'Citadel-685' : 'YEET',
    'RenaissanceTech-159' : 'YEET',
    'BankOfAmerica-710' : 'YEET',
    'WellsFargo-321' : 'YEET',
    'DeutscheBank-800' : 'YEET',
    'JPMorgan-123' : 'YEET',
    'Citi-456' : 'YEET',
    'AxeCap-789' : 'YEET',
    'PIERPOINT' : 'YEET',
    'PIERPOINT_HARPER' : 'YEET',
    'PIERPOINT_RISHI' : 'YEET',
    'PIERPOINT_YASMIN' : 'YEET',
    'PIERPOINT_ERIC' : 'YEET',
    'Fidelity-123' : 'YEET',
    'RaymondJames-456' : 'YEET',
    'UBS-789' : 'YEET',
    'MerrillLynch-101' : 'YEET',
    'Barclays-112' : 'YEET',
    'BNPParibas-113' : 'YEET',
    'CreditSuisse-114' : 'YEET',
    'GoldmanSachs-115' : 'YEET',
    'HSBC-116' : 'YEET',
    'MorganStanley-117' : 'YEET',
    'Nomura-118' : 'YEET',
    'RBC-119' : 'YEET',
    'SocieteGenerale-120' : 'YEET',
    'UBS-121' : 'YEET',
    'WellsFargo-122' : 'YEET',
    'Citigroup-123' : 'YEET',
    'DeutscheBank-124' : 'YEET',
    'JPMorgan-125' : 'YEET',
    'BankOfAmerica-126' : 'YEET',
    'BlackRock-127' : 'YEET',
    'Bridgewater-128' : 'YEET',
    'WELLSFARGO-129' : 'YEET',
    'CITIGROUP-130' : 'YEET',
    'JPMORGAN-131' : 'YEET'
}
entity = {
    'YEET_DEV' : 'NO CAP',
    'KENNETH_DEV' : 'NO CAP',
    'BROADCAP' : 'BROADCAP',
}
accounts = {
    'NO CAP' : ['GINGERBREAD','GRIME'],
    'BROADCAP' : ['MICHAEL.JONES'],
}
defaultaccounts = {
    'NO CAP' : 'GINGERBREAD',
    'guest' : 'guest'
}
