clients = {
    'YEET_DEV' : 'YEET2',
    'BROADCAP' : 'YEET',
    'KENNETH' : 'KFR',
    'OPAL' : 'YEET',
    'NM_SWEEP' : 'YEET',
    'GSCO1' : 'YEET',
    'BlackRock-452' : 'YEET',
    'Bridgewater-237' : 'YEET',
    'Citadel-685' : 'YEET',
    'RenaissanceTech-159' : 'YEET',
    'BankOfAmerica-710' : 'YEET',
    'WellsFargo-321' : 'YEET',
    'DeutscheBank-800' : 'YEET',
    'JPMorgan-123' : 'YEET',
    'Citi-456' : 'YEET',
    'AXECAP' : 'YEET',
    'PIERPOINT' : 'YEET',
    'PIERPOINT_HARPER' : 'YEET',
    'PIERPOINT_RISHI' : 'YEET',
    'PIERPOINT_YASMIN' : 'YEET',
    'PIERPOINT_ERIC' : 'YEET',
    'Fidelity-123' : 'YEET',
    'RaymondJames-456' : 'YEET',
    'UBS-789' : 'YEET',
    'MerrillLynch-101' : 'YEET',
    'Barclays-112' : 'YEET',
    'BNPParibas-113' : 'YEET',
    'CreditSuisse-114' : 'YEET',
    'HSBC-116' : 'YEET',
    'Nomura-118' : 'YEET',
    'RBC-119' : 'YEET',
    'SocieteGenerale-120' : 'YEET',
    'UBS-121' : 'YEET',
    'Citigroup-123' : 'YEET',
    'DeutscheBank-124' : 'YEET',
    'WELLSFARGO-129' : 'YEET',
    'CITIGROUP-130' : 'YEET',
    'SLOTMACHINE': 'RUGPULLZ',
    'SKRONGDESK1': 'WEAKSAUCE9',
    'DELTAZADDY': 'GAMMAWITCH',
    'SWAPGODX': 'BETAJAIL',
    'YOLOFLOW': 'RISKMANAGER',
    'HEDGIE69': 'RETAILH8R',
    'SPICEQ420': 'THETADRAIN',
    'BIGASKENERGY': 'LITPOOL69',
    'PAPERHANDZ': 'IRONVAULT',
    'IBKRBOI': 'TIKT0KTRADR',
    'SNIPERCANDLE': 'BIDWIDOW'
}
entity = {
    'YEET_DEV' : 'NO CAP',
    'KENNETH_DEV' : 'NO CAP',
    'BROADCAP' : 'BROADCAP',
}
accounts = {
    'NO CAP' : ['GINGERBREAD','GRIME'],
    'BROADCAP' : ['MICHAEL.JONES'],
}
defaultaccounts = {
    'NO CAP' : 'GINGERBREAD',
    'guest' : 'guest'
}
